config/routes.rb
NewAuthDemo::Application.routes.draw do
  resources :users, :only => [:create, :new, :show]
  resource :session, :only => [:create, :destroy, :new]
  
  get "static_pages/home"
  
  get "static_pages/about"
  
  get "static_pages/contact"

  root :to => "static_pages#home"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :password_digest, :presence => true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true, :uniqueness => true
  validates :username, :presence => true, :uniqueness => true

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def password=(unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # Expose these methods to the views
  helper_method :current_user, :signed_in?

  private

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end

  def sign_out
    current_user.try(:reset_session_token!)
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end

  def require_signed_out!
    redirect_to user_url(current_user) if signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_signed_out!, :only => [:new, :create]
  before_action :require_signed_in!, :only => [:destroy]

  def new
  end

  def create
    @user = User.find_by_credentials(
      user_params[:username],
      user_params[:password]
    )

    if @user
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    sign_out
    flash[:notice] = "You've successfully logged out."
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_in!, :only => [:show]
  before_action :require_signed_out!, :only => [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewAuthDemo</title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body data-spy="scroll" data-target=".navbar-scroll">

    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"></button>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav nav-pills">
            <li><a class="navbar-brand" href=<%= root_url %>>YoloPivot</a></li>
            <li><a href="<%= static_pages_home_url %>">Home</a></li>
            <li><a href="<%= static_pages_contact_url %>">Contact</a></li>
            <li><a href="<%= static_pages_about_url %>">About</a></li>
            
          <% if signed_in? %>
          <div class="dropdown pull-right">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
              <%= current_user.username %>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
            <li role="presentation"><%= link_to current_user.username, user_url(current_user) %></li>
            <li><%= link_to "Sign Out", session_url, :method => :delete, :id => "sign-out-link" %></li>
          </ul>
          <% else %>
            <li><button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Sign In</button></li>
            <li><%= link_to "Sign up", new_user_url %></li>
            
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Sign In</h4>
                  </div>
                  <div class="modal-body">
                    <%= render "sessions/form" %>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
            
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
    
    <% if flash[:errors] %>
      <div class="alert alert-warning" role="alert">
        <h3>Please fix the following errors:</h3>
        <ul>
          <% flash[:errors].each do |error| %>
          <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <% if flash[:notice] %>
      <div class='alert alert-success' role='alert'><%= flash[:notice] %></div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/static_pages/about.html.erb
<div class="jumbotron">
  <h1>Snappy About</h1>
  <div class='row'>
    <div class='col-xs-6'>
      <p>Bacon ipsum dolor sit amet salami short ribs ball tip meatball shankle pork belly tri-tip. Flank pork belly sirloin tongue, tri-tip jerky chuck kevin short ribs. Pork loin frankfurter pork belly short loin. Meatloaf bacon ball tip filet mignon drumstick bresaola tongue tail chicken. Swine tongue frankfurter pastrami, shankle pork loin pork belly shoulder chuck drumstick ham hock. Jerky salami landjaeger prosciutto ribeye andouille corned beef. Tail chicken chuck pork pancetta ribeye bresaola cow strip steak leberkas pork belly prosciutto.</p>
    </div>
    <div class='col-xs-6'>
      <p>Spare ribs pork chop meatloaf, hamburger swine short ribs bacon brisket venison capicola. Cow strip steak pork belly chuck pork loin ham hock corned beef short ribs t-bone capicola flank ribeye venison. Biltong pastrami hamburger jowl ball tip ham, ribeye kielbasa pork loin capicola t-bone. Strip steak shoulder biltong ground round, landjaeger leberkas turducken pork chop chuck rump bresaola pastrami short ribs chicken pancetta.</p>
    </div> 
  </div>  
</div> 

<div class='row text-center'>
  <h1>Meet the Team</h1>
  <div class='col-xs-3'>
    <img src='http://paulkiser.files.wordpress.com/2012/03/pig-smiles.jpg' class='img-circle img-responsive'>
    <h2>Porky</h2>
    <p>Moon-flower juice righteous in wrath, death before disgrace, honed and ready full of terrors the wall your grace greyscale. Darkness the seven ever vigilant, none so wise none so dutiful he asked too many questions maester. Honeyed locusts spiced wine night's watch no song so sweet no foe may pass suckling pig. Stag a taste of glory crypt, seven hells bloody mummers spiced wine never resting whore green dreams.</p>
  </div>
  <div class='col-xs-3'>
    <img src='http://img2.wikia.nocookie.net/__cb20120812082359/adventuretimewithfinnandjake/images/0/06/Pig_trans.png' class='img-circle img-responsive'>
    <h2>Piglet</h2>
    <p>As high as honor. You know nothing the wall. Nuncle cloak, none so fierce neeps, raiders arbor gold spider, ser the seven prince garron gown. Lord of light royal holdfast mulled wine. Pavilion honeyed locusts let it be written. Milk of the poppy dog. Suckling pig. Warrior brother, your grace moon-flower juice, spiced wine wildling fool, mare's milk rouse me not coin. Fire darkness old bear. Maid raiders. Never resting beware our sting. Sword arbor gold, seven hells, bloody mummers, honeyed locusts, craven. Ever vigilant, tread lightly here neeps, spider work her will, green dreams maidenhead death before disgrace. Mulled wine joust dwarf. Night's watch. Suckling pig. Pride and purpose, spiced wine, the seven, garron brothel, wench. Spearwife never resting, half-man betrothed, your grace, mare's milk, tunic. Bloody mummers none so wise.</p>
  </div>
  <div class='col-xs-3'>
    <img src='https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS-DnZcPTyL7JMk7XBA6RN9zMA4iz3ALOSLmLTKO1rDF3HFEh1N' class='img-circle img-responsive'>
    <h2>Ham</h2>
    <p>Honeyed locusts, in his cups ice, old bear ever vigilant, bastard we do not sow summerwine. None so dutiful your grace. Warg suckling pig always pays his debts. Slave arbor gold. You know nothing merchant. None so fierce the seven. The last of the dragons. The wall, take the black slay, ours is the fury, lord of light tread lightly here. Spiced wine. Righteous in wrath. Spare me your false courtesy. Steel always pays his debts. Moon and stars, flagon spider, gown beast, night's watch, dwarf. Our sun shines bright. Drink, your king commands it. Death mare's milk ironborn. Fleet trueborn. Sword maid. No song so sweet.</p>
  </div>
  <div class='col-xs-3'>
    <img src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-onfJMlaXETqdHaYxeHYKiDqf_NHGdRbm5WnxvM6pGb3_p4yJ' class='img-circle img-responsive'>
    <h2>Pinky</h2>
    <p>Honeyed locusts, green dreams old bear, godswood nightsoil never resting, ever vigilant we light the way joust. Servant fire. Honed and ready, spiced wine, your grace, raiders dwarf, gown. None so wise. Wench the wall gargoyles. Moon-flower juice half-man the seven. Beware our sting feast. Death before disgrace. Night's watch a taste of glory. Your grace suckling pig trueborn. Wildling tourney princess. Sword in his cups rouse me not brother none so dutiful old bear. Always pays his debts treachery. Green dreams. Weirwood lord of light arakh. Godswood crimson feed it to the goats.</p>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>Contact</h1>
    <form class="contact-form" role="form">
      <div class="form-group">
        <label class="control-label" for="user_username">Name</label>
        <input
           id="user_username"
           name="user[username]"
           type="text"
           class="form-control"
           placeholder="Enter name">
      </div>
      <div class="form-group">
        <label class="control-label" for="user_username">Phone Number</label>
        <input
           id="user_username"
           name="user[username]"
           type="text"
           class="form-control"
           placeholder="Enter phone number">
      </div>
      <input type="button" value="contact" class="btn btn-default" id="contact-form-button">
    </form>
  </div>
  <div class="col-xs-6">
    <h1>Right Col</h1>
    <table class="table table-striped">
      <tr>
        <td>Jill</td>
        <td>8675430</td>
      </tr>
      <tr>
        <td>Bill</td>
        <td>867230</td>
      </tr>
      <tr>
        <td>Will</td>
        <td>8634430</td>
      </tr>
      <tr>
        <td>Dill</td>
        <td>8611430</td>
      </tr>
    </table>
  </div>
</div>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post" role="form">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
     
  <div class="form-group">
    <label for="user_username">Username</label>
    <input
       id="user_username"
       name="user[username]"
       type="text"
       class="form-control"
       placeholder="Enter email">
  </div>

  <div class="form-group">
    <label for="user_password">Password</label>
    <input
       id="user_password"
       name="user[password]"
       type="password"
       class="form-control"
       placeholder="Enter password">
  </div>

  <input type="submit" value="<%= message %>" class="btn btn-default">
</form>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, dear user!</p>